# ================= Training Configurations =================
#   python train.py
train:
  datapath: '/media/wyh/data' # 训练和验证时使用的数据集根目录
  benchmark: 'pascal'
  logpath: 'pascal_resnet50_run_none'               #！！！！！
  backbone: 'resnet50' # 'vgg16' or 'resnet50'
  fold: 4             # 0, 1, 2, 3, 4
  lr: 0.002
  bsz: 12
  niter: 2000
  nworker: 8

  power: 0.9  # Poly LR 策略的指数
  warmup: true              # 是否启用 Warmup 功能
  warmup_iters: 500         # Warmup 持续的迭代次数
  early_stopping_patience: 80


# ======================= 恢复训练配置 =======================
#   Additionally saved checkpoint to
  resume: 0                # 设置为 True 来激活“恢复训练”模式
  load_path: ''           # 上一次的最佳权重路径
  start_epoch:           # 从第 x 轮开始
# ==========================================================

# ================= Testing Configurations ==================
#   python test.py
test:
  datapath: '/media/wyh/data' # 测试时使用包含所有数据集的根目录
  load_model_path: '/media/wyh/PAT/logs/pascal_resnet50_run1/model_epoch_10_miou_71.94.pt' # 训练后生成的模型路径
  backbone: 'resnet50'

  # --- 在这里选择要测试的数据集 ---
  benchmark: 'lung'  # 'fss', 'isic', or 'lung'
  nshot: 1           # 1 or 5
  bsz: 30
  nworker: 8